Repository Weather-Vortex/weather-vortex-client, pull requests merged in 2021-08, with the labels that each got.

#11 Router view
  package-lock.json
  package.json
  src/App.vue
  src/components/AppBar.vue
  src/components/HelloWorld.vue
  src/components/NavigationDrawer.vue
  src/main.js
  src/state/index.js
Labels: documentation, enhancement

#12 User icon
  src/components/AppBar.vue
  src/components/UserIcon.vue
  src/router/index.js
  src/views/User.vue
  src/views/users/Login.vue
  src/views/users/Profile.vue
  src/views/users/PublicProfile.vue
  src/views/users/Register.vue
Labels: enhancement

#13 Unit tests
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  tests/unit/example.spec.js
Labels: enhancement

#14 Check server status
  .env.examples
  .gitignore
  LICENSE
  README.md
  package-lock.json
  package.json
  src/components/HelloWorld.vue
  src/components/info/CheckStatus.vue
  src/components/info/InfoCard.vue
  src/components/info/InfoMain.vue
  src/main.js
  src/views/About.vue
  src/views/Home.vue
Labels: enhancement

#22 Weather forecast component
  package.json
  src/components/HelloWorld.vue
  src/components/info/CheckStatus.vue
  src/components/info/InfoCard.vue
  src/components/info/InfoMain.vue
  src/components/weather/QuickForecastCard.vue
  src/router/index.js
  src/state/index.js
  src/views/Forecasts.vue
  src/views/Home.vue
  tests/unit/setup.js
Labels: enhancement

#34 Position acquire geolocation
  package-lock.json
  package.json
  src/components/weather/QuickForecastCard.vue
  src/main.js
Labels: question

#41 Fix drawer scrolling
  package-lock.json
  package.json
  src/App.vue
  src/assets/clouds.jpg
  src/assets/lavender.jpg
  src/assets/user.png
  src/components/AppBar.vue
  src/components/Footer.vue
  src/components/NavigationDrawer.vue
  src/components/info/InfoCard.vue
  src/components/info/InfoMain.vue
  src/components/user/PrivateUserCard.vue
  src/components/user/PrivateUserControlUnits.vue
  src/components/user/PrivateUserReviews.vue
  src/components/user/PublicUserCard.vue
  src/components/weather/QuickForecastCard.vue
  src/main.js
  src/views/User.vue
  src/views/users/Login.vue
  src/views/users/Profile.vue
  src/views/users/PublicProfile.vue
  src/views/users/Register.vue
  src/views/users/clouds.jpg
Labels: bug

#49 Env var gh pages
  .github/workflows/deploy.yml
Labels: bug
